export const INITIAL_TECHNIQUES: Record<string, { singles: string[]; combos: string[]; exclusive?: boolean; label?: string; title?: string; description?: string }> = {
  // Nak Muay Newb - Start here to learn the Art of 8 Limbs
  newb: {
    label: 'newb',
    title: 'Nak Muay Newb',
    description: 'Start here to learn the basic strikes',
    singles: [
      "Jab",
      "Cross",
      "Left Hook",
      "Right Hook",
      "Left Uppercut",
      "Right Uppercut",
      "Overhand",
      "Jab to the Body",
      "Cross to the Body",
      "Left Hook to the Body",
      "Right Hook to the Body",
      "Left Teep",
      "Right Teep",
      "Left Check",
      "Right Check",
      "Inside Leg Kick",
      "Switch Kick",
      "Low Kick",
      "Middle Kick",
      "Head Kick",
      "Left Knee",
      "Right Knee",
      "Duck",
      "Slip Left",
      "Slip Right",
      "Lean Back",
      "Pivot Left",
      "Pivot Right",
      "Roll Right",
      "Roll Left",
      "Long Guard",
      "High Guard Block"
    ],
    combos: [
      "1, Right Low Kick",
      "1 2",
      "1 1 2",
      "1 2 3",
      "1 2, Right Body Kick",
      "1 2, Left Body Kick",
      "1 2 3, Right Low Kick",
    ],
    exclusive: true
  },

  khao: {
    label: 'khao',
    title: 'Muay Khao',
    description: 'Close-range clinch work and knee combinations',
    // Close-range, clinch-focused combos and strikes
    singles: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "1 to the body", 
      "2 to the body", 
      "3 to the body",
      "Left teep",
      "Right teep",
      "Left Knee",
      "Right Knee",
      "Left Check",
      "Right Check",
      "Left Kick",
      "Right Kick",
      "Left Elbow",
      "Right Elbow",
      "Spinning Elbow"
    ],
    combos: [
      "1, Step-in, Right Knee, Pivot Left",
      "2, Step-in, Left Knee",
      "High Block March, Left Knee, Right Knee",
      "1 2, Clinch, Double Knees",
      "1 4, Switch Knee, Elbow",
      "Left Check, 2 3 2, Right Knee",
      "Right Check, 3 2 3, Left Knee",
      "2, Left Elbow, Right Elbow",
      "Knee, Elbow, Knee",
      "1 2, 3 to the Body, 3 to the Head",
      "Knee, Knee, Knee",
      "1 4, Switch Knee"
    ]
  },

  mat: {
    label: 'mat',
    title: 'Muay Mat',
    description: 'Blending Heavy hands with Kicks and Knees',
    singles: [
      "1", "2", "3", "4", "5", "6",
      "Left Teep", "Right Teep", "Left Knee", "Right Knee", "Left Check",
      "Right Check", "Left Kick", "Right Kick",
      "Left Elbow", "Right Elbow",
    ],
    combos: [
      "1 2 3",
      "3, Low Kick, 3",
      "2, Inside Leg Kick, 2 3",
      "1, 2 to the Body, 3 to the Head",
      "Overhand, Left Knee, 6 3",
      "Catch Body Kick, 2 3",
      "1, Overhand, 3 to the Body, 3 to the Head",
      "1 2 3, Step-in Right Elbow",
      "1 1 2",
      "2 3 2",
      "1 to the Body, 2",
      "Overhand, 4 to the Body, 3 to the Body",
    ]
  },

  tae: {
    label: 'tae',
    title: 'Muay Tae',
    description: 'Kicking specialist with long-range attacks',
    singles: [
      "1", "2", "3", "4", "5", "6",
      "Left Teep", "Right Teep", "Left Knee", "Right Knee",
      "Left Check", "Head Kick",
      "Right Check", "Left Kick", "Right Kick", "Left Check",
      "Right Check", "Left Check",
      "Left Elbow", "Right Elbow",
    ],
    combos: [
      "1, Right Kick",
      "Right Kick, Right Kick", "Left Kick, Left Kick",
      "1 2, Switch Kick",
      "Right Kick, Left Kick",
      "Left Teep, Right Kick",
      "Right Kick, Right Teep",
      "Right Low Kick, Right High Kick",
      "2 3, Spinning Back Kick",
      "Inside Leg Kick, Switch Kick",
      "2 3, Low Kick, Right Check",
      "1 1 2, Low Kick",
      "3 2, Low Kick",
      "1 2, Right Kick, Left Kick",
    ]
  },

  femur: {
    label: 'femur',
    title: 'Muay Femur',
    description: 'Technical timing and defensive counters',
    singles: [
      "1", "2", "3", "4", "5", "6",
      "Left Teep", "Right Teep", "Left Knee", "Right Knee", "Left Check",
      "Right Check", "Flying Knee", "Left Kick", "Right Kick", "Head Kick",
      "Left Elbow", "Right Elbow", "Spinning Elbow", "Question Mark Kick",
      "Sweep Left", "Sweep Right", "Left Check", "Right Check",
    ],
    combos: [
      "Right Check, Right Low Kick",
      "6 3, Right Knee, Right Elbow",
      "Parry Jab, Left Kick",
      "Lean Back, Right Low Kick",
      "Left Teep, Right Knee, Sweep Left",
      "Thai Hop, Axe Elbow",
      "Inside Leg Kick, Switch Knee",
      "1, Shift Left, Head Kick",
      "1, Shift Right, Head Kick",
      "Catch Kick, 2 3, Right Knee, Sweep Right",
      "Catch kick, Sweep the leg",
      "Parry Jab, 1 2 3, Right Kick",
      "Right Kick, Right Teep",
      "Right Teep, Question Mark Kick",
      "Step Through, Left Kick",
      "Left Teep, Switch Knee, Right Elbow",
      "Switch Kick, 2 3 2",
      "1, Lean Back, Cross, Low Kick",
      "2, Switch Kick, 2 3, Low Kick",
      "Feint Teep, 2 3",
      "Parry, 2, Rear Kick",
      "Lean Back, Counter Right Kick",
      "Slip Right, 2 3, Sweep Right",
      "Switch Kick, 2, Pivot Left",
      "Fake Kick, 2 3",
      "Teep, Step-in Right Elbow",
      "Oley Left, Head Kick",
      "Parry, 2 3, Right Teep",
      "1, Lean Back, 2, Low Kick"
    ]
  },

  sok: {
    label: 'sok',
    title: 'Muay Sok',
    description: 'Vicious elbows and close-range attacks',
    singles: [
      "1", "2", "3", "4", "5", "6",
      "Left Teep", "Right Teep", "Left Knee", "Right Knee", "Left Check",
      "Right Check", "Left Kick", "Right Kick",
      "Left Elbow", "Right Elbow", "Axe Elbow", "Spinning Elbow",
    ],
    combos: [
      "1 2, Right Elbow",
      "1, Right Elbow",
      "3, Right Elbow",
      "Parry Jab, Left Up Elbow",
      "2, Roll Right, Right Elbow",
      "Clinch, Left Up Elbow, Right Elbow",
      "Left Elbow, Right Elbow, Left Elbow",
      "1 1 2, Jumping Elbow",
      "2 3, Right Up Elbow",
      "Switch Knee, Right Elbow",
      "1 2 3, Spinning Elbow"
    ]
  },

  boxing: {
    label: 'boxing',
    title: 'Boxing',
    description: 'Fundamental boxing combinations',
    singles: [
      "Jab", "Cross", "3", "4", "5", "6", "Overhand", 
      "High Guard Block", "Parry Jab", "Catch Cross",
      "1 to the Body", "2 to the Body", "3 to the Body", 
      "Pivot Left",  "Pivot Right", "Duck",
    ],
    combos: [
      "1 1 2",
      "1 2 3",
      "1 2 3 2",
      "1 2 5 2",
      "2 3 2",
      "3 3 3",
      "2 2 2",
      "1, Slip Right, 2",
      "1 2, 3 to the Body, 3 to the Head",
      "1 2, Roll Right, 2 3",
      "2 3, Roll Left, 3 2",
      "1, 2 to the Body, 3 to the Head",
      "1 2",
      "1, Slip Left, 5 2, Pivot Left",
      "2, Slip Right, 6 3, Pivot Right"
    ]
  },

  calisthenics: {
    singles: [
      "1 Burpee",
      "High Knees",
      "Alternating Checks",
      "Jumping Jacks",
      "1 2 1 2 1 2",
      "2 3 2 3 2 3",
      "3 Jumpsquats",
      "3 Speed Kicks Left",
      "3 Speed Kicks Right",
      "Left Check Right Check",
      "Right Check, Left Check",
    ],
    combos: []
  },

  two_piece: {
    label: 'two_piece',
    title: 'Two-Piece Combos',
    description: 'Short, powerful 2-strike combinations',
    singles: [],
    combos: [
      "1 2",
      "2 3",
      "3 4",
      "5 6",
      "6 3",
      "1, Right Kick",
      "2, Switch Kick",
      "2, Low Kick",
      "3, Right Kick",
      "Right Teep, 2",
      "2, Left Knee",
      "1, Right Knee",
      "3, Right Elbow",
      "1, Right Elbow",
      "Inside Leg Kick, 2",
      "Inside Leg Kick, Left Kick",
      "3, Low Kick",
      "Right Kick, 3",
      "Left Teep, Right Kick",
      "Left Teep, Switch Kick",
      "Right Kick, 2"
    ]
    // NOTE: added empty 'singles' to satisfy the required type; emphasis remains combos-focused
  },

  southpaw: {
    label: 'southpaw',
    title: 'Southpaw',
    description: 'Left-handed stance with combos tailored for southpaw fighters',
    singles: [],
    combos: [
      "1 2",
      "1 1 2",
      "1 2 3",
      "1 2, 3 to the Body",
      "Slip Outside, 2 to the Body, 3 to the Head",
      "1 2, Pivot Left, 2",
      "1 2, Left Uppercut, 3",
      "Feint 1, Step Outside, 2, 2 to the Body",
      "3, Overhand, 2 3",
      "1, Slip, 2 3 2",
      "1 2, Left Body Kick",
      "1 2 3, Right Low Kick",
      "Left Teep, 2, Left Round Kick",
      "1, 2 to Body, Left High Kick",
      "1 2 3, Left Low Kick",
      "1 2, Switch Kick, 2",
      "Left Teep, 2, Clinch, Right Knee, Left Elbow",
      "Feint Left Kick, 1 2, Left Kick",
      "1 2 3, Left Elbow, Pivot Left",
      "1 1 2, Left Kick, Clinch, Double Knees"
    ]
  },

  meat_potatoes: {
    label: "meat_potatoes",
    title: "Meat & Potatoes",
    description: "Classic, high-percentage strikes and combos for all levels",
    singles: [
      "Jab",
      "Cross",
      "Left Hook",
      "Right Kick",
      "Left Body Kick",
      "Right Low Kick",
      "Left Teep",
      "Right Teep"
    ],
    combos: [
      "1 2, Right Kick",
      "2 3, Low Kick",
      "1 2 3 2, Low Kick",
      "1, Rear Teep",
      "2 3, Rear Kick",
      "1 1 2, Left Body Kick",
      "Slip, 2, Right Kick",
      "1 2, Switch Kick",
      "2, Low Kick",
      "1 2 3, Right Kick",
      "1 2, Left Elbow",
      "1 2 3,Right Uppercut Elbow",
      "Left Kick, 2 3, Right Low Kick",
      "Right Kick, 3 2, Left Body Kick",
      "Left Teep, 2 3, Right Low Kick", 
      "1 3 2, Left Body Kick"
    ]
  },
  buakaw: {
    label: "buakaw",
    title: "Buakaws Corner",
    description: "Aggressive clinch, knees, and sweeps inspired by Buakaw",
    singles: [
      "Jab",
      "Cross",
      "Left Hook",
      "Left Knee",
      "Right Knee",
      "Clinch",
      "Elbow",
      "Teep",
      "Sweep Right"
    ],
    combos: [
      "1, Step-in Clinch, Double Knees",
      "2, Long Guard, Rear Knee",
      "1 2, Clinch, Knee, Elbow",
      "Left Teep, Step-in, Double Knees",
      "Long Guard, Knee, Knee, Elbow",
      "1 4, Clinch, Double Knees",
      "Inside Low Kick, Clinch, Knee",
      "2, Clinch , Sweep Right",
      "Clinch Break, Elbow, Left Kick",
      "Switch Kick Switch Kick Switch Kick",
      "Catch Kick, Clinch, Knee"
    ]
  },
  low_kick_legends: {
    label: "low_kick_legends",
    title: "Low Kick Legends",
    description: "Devastating low kicks and classic Dutch-style combinations",
    singles: [
      "Cross",
      "Left Hook",
      "Right Low Kick",
      "Inside Low Kick",
      "Switch Kick",
      "Slip Right",
      "Overhand",
      "Double Jab"
    ],
    combos: [
      "1 2, Low Kick",
      "2 3, Low Kick",
      "1 1 2, Low Kick",
      "Overhand, Low Kick",
      "Slip, 2, Low Kick",
      "Inside Low Kick, 2",
      "3, Low Kick, 3",
      "2, Low Kick, Switch Kick",
      "Low Kick, High Kick"
    ]
  },
  elbow_arsenal: {
    label: "elbow_arsenal",
    title: "Elbow Arsenal",
    description: "Sharp elbow strikes and creative close-range attacks",
    singles: [
      "Jab",
      "Cross",
      "Left Hook",
      "Right Elbow",
      "Left Elbow",
      "Spinning Elbow",
      "Step-in Elbow",
      "Up Elbow",
      "Clinch"
    ],
    combos: [
      "1 2, Step-in Elbow",
      "3, Rear Elbow",
      "2, Up Elbow",
      "1, Pull Back, Up Elbow",
      "Clinch Break, Spinning Elbow",
      "Rear Kick, Step-in Elbow",
      "2, Left Elbow, Right Elbow",
      "1 4, Elbow, Knee",
      "Slip, Elbow",
      "Jumping Elbow, Cross"
    ]
  },
  ko_setups: {
    label: "ko_setups",
    title: "KO Setups",
    description: "Explosive knockout setups and finishing combinations",
    singles: [
      "Jab",
      "Cross",
      "Left Hook",
      "Overhand",
      "Right Kick",
      "Left High Kick",
      "Slip",
      "Rear Knee",
      "Elbow"
    ],
    combos: [
      "1 2, Head Kick",
      "Slip Right, 2, Rear Kick",
      "Right Low Kick, Right Head Kick",
      "1 1 2, Head Kick",
      "2 3, Head Kick",
      "1 2 3, Overhand",
      "Slip, 6 3 2",
      "Overhand, 3 to the Body, Low Kick",
      "2, Rear Knee, Elbow",
      "Teep, Step-in, Head Kick"
    ]
  },

  tricky_traps: {
    label: "tricky_traps",
    title: "Tricky Traps and Spinning Shit",
    description: "Advanced spinning techniques and deceptive setups",
    singles: [
      "1",
      "2",
      "3",
      "4",
      "Teep",
      "Body Kick",
      "Low Kick",
      "Overhand",
      "Question Mark Kick",
      "Step-Off Elbow",
      "Spinning Elbow",
      "Spinning Back Kick",
      "Spinning Hook Kick",
      "Spinning Heel Kick",
      "Jump Switch Knee",
      "Flying Knee"
    ],
    combos: [
      "1, Step back, Spinning Elbow",
      "Teep, Pull back, Spinning Heel Kick",
      "1 2, Slip, Spinning Elbow",
      "Low Kick, Fake Switch Kick, Spinning Hook Kick",
      "Check Kick, 2, Spinning Elbow",
      "1, Slip Left, Spinning Elbow",
      "Fake Teep, Jump Switch Knee, Spinning Back Kick",
      "1 2 3, Duck, Spinning Elbow",
      "Body Kick, Spin Through, Back Kick",
      "Fake 1 to the body, Step Off, Spinning Hook Kick",
      "Overhand Right, Spinning Elbow",
      "3 2, Spinning Elbow",
      "1 1, Inside Low Kick, Spinning Back Kick",
      "Right Kick, Right Teep, Question Mark Kick",
      "Inside Foot Sweep, Switch Knee",
      "Low Kick, Feint Low Kick, Sweep Right",
      "Low Kick, Feint Low Kick, Spinning Hook Kick",
      "1 4, Spinning Elbow"
    ]
  },

  feints_and_fakeouts: {
    label: "feints_and_fakeouts",
    title: "Feints and Fakeouts",
    description: "Deceptive movements and setups that manipulate timing and rhythm.",
    singles: [
      "Jab Feint",
      "Shoulder Feint",
      "Body Jab Feint",
      "Teep Feint",
      "Low Kick Feint",
      "Body Kick Feint",
      "Step Feint",
      "Retreat Feint",
      "Switch Step Feint",
      "Guard Bait",
      "Lazy Teep",
      "Limp Feint",
      "Double Teep Feint",
      "Hand Trap",
      "Pattern Break"
    ],
    combos: [
      "Fake the Jab, Cross",
      "Shoulder Feint, 1 2",
      "Body Feint, Overhand Right",
      "Teep Feint, Right Kick",
      "Low Kick Feint, High Kick",
      "Fake the Body Kick, 2 3 Low Kick",
      "Step Feint, Teep",
      "Retreat Feint, 2 3 2",
      "Switch Step Feint, Right Kick",
      "Guard Bait, Slip Cross",
      "Lazy Teep, Step-in Cross",
      "Limp Feint, Switch Kick",
      "Double Teep Feint, Jump Knee",
      "Body Kick Feint, Spinning Elbow",
      "Hand Trap, Elbow"
    ]
  },

  dutch_kickboxing: {
    label: "dutch_kickboxing",
    title: "Dutch Kickboxing",
    description: "High-pressure combinations emphasizing volume, flow, and low kicks.",
    singles: [
      "1",
      "2",
      "3",
      "4",
      "Low Kick",
      "Body Kick",
      "Head Kick",
      "Inside Low Kick",
      "Switch Kick",
      "Teep",
      "Overhand",
      "Step-in Knee",
      "Slip and Counter",
      "Check and Return",
      "Angle Off Hook"
    ],
    combos: [
      "1 2, Left Hook, Right Low Kick",
      "1 2 3, Low Kick",
      "2 3 2, Left Body Kick",
      "1 2, Right Check, Right Low Kick",
      "1 2, 3 to the Body, Right Low Kick",
      "1 2 3, Switch Kick",
      "1 1 2 3, Right Kick",
      "1 2, Step Left, 3, Right Kick",
      "Slip Right, 2 3, Low Kick",
      "1 2 5 2 3, Right Kick",
      "2 3 6 1 2, Left Kick",
      "2 3 2, Step-in Knee",
      "1 2 3, Right Body Kick",
      "1 2 3, 3, Low Kick",
      "1 2, Slip, 2, Left Kick",
      "2 3, Overhand, Left Kick",
      "1 2 3, Switch Low Kick",
      "1 2, Inside Leg Kick, 6 2 3",
      "1 2, 3 to the body, Right Body Kick"
    ]
  },
};

export default INITIAL_TECHNIQUES;