// Define thumbnails for groups (example mapping)
export const GROUP_THUMBNAILS: Record<string, string> = {
  timer_only: "/assets/icon.stopwatch.png",
  newb: "/assets/icon_newb.png",
  two_piece: "/assets/icon_two_piece.png",
  boxing: "/assets/icon_boxing.png",
  mat: "/assets/icon_mat.png",
  tae: "/assets/icon_tae.png",
  khao: "/assets/icon_khao.png",
  sok: "/assets/icon_sok.png",
  femur: "/assets/icon_femur.png",
  southpaw: "/assets/icon_southpaw.png",
  muay_tech: "/assets/icon.muaytech.png",
  meat_potatoes: "/assets/icon_meat_potatoes.png",
  buakaw: "/assets/icon.buakaw.png",
  low_kick_legends: "/assets/icon_lowkicklegends.png",
  elbow_arsenal: "/assets/icon.elbow arsenal.png",
  ko_setups: "/assets/icon.ko.png",
  tricky_traps: "/assets/icon.trickytraps.png",
  feints_and_fakeouts: "/assets/icon.feintsandfakes.png",
  dutch_kickboxing: "/assets/icon.dutch.png",
};

// Home page order (excluding user and calisthenics)
export const CORE_ORDER = [
  "timer_only",
  "newb",
  "two_piece",
  "boxing",
  "mat",
  "tae",
  "khao",
  "sok",
  "femur",
  "southpaw",
  "muay_tech",
  "meat_potatoes",
  "buakaw",
  "low_kick_legends",
  "elbow_arsenal",
  "ko_setups",
  "tricky_traps",
  "feints_and_fakeouts",
  "dutch_kickboxing",
];
